### ISSUE TITLE
我想知道新的网易云音乐搜索等接口的加密过程

### ISSUE THREAD

**Issue by scatteredwriter** [bieberg0n/blog#14]
麻烦可以提供一下么，谢谢
scatteredwriter@qq.com

**Comment by bieberg0n** [comment]
目前可以找到的关于新接口的资料有:
[网易云音乐新版WebAPI分析](https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%89%88WebAPI%E5%88%86%E6%9E%90%E3%80%82)(登录失效,获取用户歌单,获取歌单详情,获取歌曲URL可能还能用.加密过程与文里的登录的加密方式相同)
[如何爬网易云音乐的评论数？](https://www.zhihu.com/question/36081767/answer/65820705)(获取评论)

至于搜索的新版api暂时没有资料,可以继续使用旧版api:[网易云音乐API分析](https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90API%E5%88%86%E6%9E%90).
